final cleanup

diff --git a/.github/workflows/update-docs.yml b/.github/workflows/update-docs.yml
--- a/.github/workflows/update-docs.yml
+++ b/.github/workflows/update-docs.yml
@@ -5,33 +5,34 @@ name: Update Docs
 on:
 # Anyone can trigger this workflow as the repository is public.   
   repository_dispatch:
-    types: [trigger-from-apps-repo] 
-  pull_request:
-    paths:
-      - '.github/workflows/update-docs.yml'
+    types: [trigger-docs-update] 
+  # uncomment this to test outside of main branch:
+  # pull_request:
+  #   paths:
+  #     - '.github/workflows/update-docs.yml'
 
 jobs:
-  # This is a sanity check to make sure the trigger is coming from the apps repo
+  # This is a sanity check to make sure the trigger is coming from the sdk repo
   # if not, we will fail the workflow and it will not run the rest of the jobs
-  # validate-trigger:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Validate webhook secret
-  #       env:
-  #         EXPECTED_SECRET: ${{ secrets.APPS_WEBHOOK_SECRET }}
-  #         RECEIVED_SECRET: ${{ github.event.client_payload.secret }}
-  #       shell: bash
-  #       run: |
-  #         if [[ "${EXPECTED_SECRET}" != "${RECEIVED_SECRET}" ]]; then
-  #           echo "Invalid webhook secret"
-  #           exit 1
-  #         fi
-  #         echo "Webhook validation successful"
+  validate-trigger:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate webhook secret
+        env:
+          EXPECTED_SECRET: ${{ secrets.WEBHOOK_SECRET }}
+          RECEIVED_SECRET: ${{ github.event.client_payload.secret }}
+        shell: bash
+        run: |
+          if [[ "${EXPECTED_SECRET}" != "${RECEIVED_SECRET}" ]]; then
+            echo "Invalid webhook secret"
+            exit 1
+          fi
+          echo "Webhook validation successful"
 
   update-docs:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout centrifuge/apps repository
+      - name: Checkout centrifuge/sdk repository
         uses: actions/checkout@v4
         with:
           repository: centrifuge/sdk
